added fwhm_ivar kwarg to noise_models
ACTCollaboration/mnms pull request #9
Opened 2022-03-14 19:45 UTC by AdriJD

If provided, the code uses smoothed ivar maps. This helps the tiled model in cases where the ivar maps have so much  small-scale structure that weighting the data by the unsmoothed ivar maps actually makes the stationarity of the noise worse. Before smoothing the ivar maps I inpaint the unobserved parts with the median of the observed pixels. This helps a little bit with avoiding biasing the ivar low at the edges of the map. Not perfect, but I think good enough for now. Using the option will add even more information to the filenames, but that is okay for now. We are going to change the handling of the metadata in the future.

2022-03-15 15:50 UTC, zatkins2 requested changes

2022-03-15 15:50 UTC, zatkins2 commented on mnms/noise_models.py
> +                        self._ivar = utils.smooth_gauss_masked(
It shouldn't matter because the name `self._ivar` will get overwritten when this function call returns, but it would be better if this function were just called with no assignment (since it's already inplace).

2022-03-15 17:54 UTC, zatkins2 commented on mnms/utils.py
> +def smooth_gauss_masked(imap, fwhm, mask_bool, inplace=False):
Did you make this function without looking at `utils.smooth_gauss` in the `fsaw_model` branch? If so, that's a funny coincidence. They differ slightly in signature and implementation but do essentially the same thing, so we should decide what to keep from each and go with one function moving forward.

2022-04-14 20:02 UTC, zatkins2 requested changes
Should just be one more easy commit:

Can you add fwhm_ivar to steerable model?

Thanks!

2022-04-14 20:02 UTC, zatkins2 commented on mnms/inpaint.py
> +    mask_bool = mask_bool.astype(bool, copy=False)
Is this line doing anything?

2022-04-14 20:15 UTC, AdriJD commented
I've added the option to the fsaw model

2022-04-14 20:17 UTC, zatkins2 approved these changes

2022-04-14 20:17 UTC, merged